CREATE TABLE skill (
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  reference VARCHAR(64) NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  account_id BIGINT NOT NULL,
  FOREIGN KEY (account_id) REFERENCES account(id) ON UPDATE CASCADE ON DELETE CASCADE
);